// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://feszywpfxuxbvepcirxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZlc3p5d3BmeHV4YnZlcGNpcnhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MDE0NzgsImV4cCI6MjA1ODM3NzQ3OH0.v2V0P1_APWa2VoAcFYRk1xbxcOdXdgWI92BCFvoaEjc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);